### ISSUE TITLE
Add bibliographic numbering on hand-crafted references

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#103]
I note that all bibliographic references have their numbering attached
at the end:

![issue1-3](https://user-images.githubusercontent.com/33627611/179249268-185ec19d-9ef2-4f4d-b0d6-e7c3a182d5e8.PNG)

![issue1-1](https://user-images.githubusercontent.com/33627611/179248779-7918b4d6-408a-487f-8b51-c63866fbe14a.PNG)

But if the reference is to be hand-crafted:

```adoc
... and tutorial information can be found in
<<Shenck,Schenk and Wilson>>.
````

The numbering is not added:

![issue1-2](https://user-images.githubusercontent.com/33627611/179249017-4f3d4b38-d6ec-4902-b488-598d9986e532.PNG)

**Comment by opoudjis** [comment]
You're providing the rendering text:

`<<Shenck,Schenk and Wilson>>.`

The "Schenk and Wilson" text is overriding the entire machine generated citation, including the [B7]; and in my opinion it should.

The "Schenk and Wilson" will in fact be autogenerated... if you provide a properly formatted reference, so it can extract the surnames. 

`* [[[Shenck,The EXPRESS Way]]], Schenk, D. A., and Wilson, P. R., _Information Modeling_: The EXPRESS Way. New York: Oxford University Press, 1994.`

is not a properly formatted reference.

Because of the ongoing lack of project management, workarounds like https://github.com/metanorma/metanorma-standoc/issues/319 https://github.com/metanorma/metanorma-iso/issues/681 have not been explored.

The solution of me appending [B7] to your provided "Schenk and Wilson" is wrong. You don't know that there won't be a context in which we won't be required to suppress that bibliographic number. It's IEEE, they are certainly capable of it. So I will not do that.

There are five solutions:

1. By default, append [B7] to the provided "Schenk and Wilson" text, and add a flag to suppress that behaviour optionally. No. There are way too many exceptions and special cases in bibliographic references already, I will not do that.
2. You append [B7] to the provided "Schenk and Wilson" text. No, the numbers change every time you add a new reference, you will not do that.
3. Add the Schenk and Wilson reference as an AsciiBib reference. AsciiBib is becoming worse and worse as an option, especially now that the hash import function has been hijacked for export to YAML. It's our fallback, but we are looking to get out of it.
4. Implement BibTeX import. I need help with that.
5. Implement the start of microformatting of fields in formatted references, https://github.com/metanorma/metanorma-iso/issues/681

I'm going to go with that. I'm going to implement some basic microformatting as spans: contributor, surname, initials, given name, title, pubyear, docid --- enough to extract semantics for use alongside the formatted reference.

**Comment by opoudjis** [comment]
I am now marking up the required information in the bibliography, so given

````
* [[[Shenck,The EXPRESS Way]]], s:surname[Schenk], D. A., and s:surname[Wilson], P. R., s:title[_Information Modeling_: The EXPRESS Way]. New York: Oxford University Press, s:pubyear[1994].
````

I am generating

````
<bibitem id="Shenck">
  <formattedref format="application/x-isodoc+xml">Schenk, D. A., and Wilson, P. R., <em>Information Modeling</em>: The EXPRESS Way. New York: Oxford University Press, 1994. [The EXPRESS Way] </formattedref>
  
  <title><em>Information Modeling</em>: The EXPRESS Way</title>
  <docidentifier>The EXPRESS Way</docidentifier><docidentifier type="metanorma-ordinal">[B7]</docidentifier>
  <date type="published">1994</date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        
        <surname>Schenk</surname>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        
        <surname>Wilson</surname>
      </name>
    </person>
  </contributor>
</bibitem>
````

I remain very far from a solution, for the following reasons.

1. IEEE have given zero guidance on whether to use Author/Name or Title-based citations, because in their typical lackadaisical fashion, they allow either. So I have implemented Title-based citations, as less problematic. The fact that novel requirements keep jumping out of me in this accursed flavour, such as Author/Name citations, makes me furious.
2. Moreover, the fake identifier "The EXPRESS Way" is being appended to the Title-based citations, instead of B7, giving as the default citation `<eref type="inline" bibitemid="Shenck" citeas="The EXPRESS Way">Information Modeling: The EXPRESS Way The EXPRESS Way</eref>`.

So I now need to:

1. Specify a configuration to generate author/date based citations, plus disambiguating letters, instead of titles.
2. Debug so that the ordinal tag is appended to the citation, instead of the user-nominated identifier.

(1) requires the implementation of https://github.com/metanorma/isodoc/issues/159 in relaton-render, which will gather up all author-date  citations from a document, and apply disambiguating letters.

I need yet another distraction like a hole in the head, so (1) can good and wait. I'll debug (2), and then put this ticket back on hold, because there is far too much else going on.

**Comment by opoudjis** [comment]
citeas: the bibitem default docidentifier, for items that are not standards, needs to be metanorma-ordinal, and not whatever dummy identifier has been provided.

**Comment by opoudjis** [comment]
Now Presentation XML is: `<eref type="inline" bibitemid="Shenck" citeas="[B7]">Information Modeling: The EXPRESS Way [B7]</eref>` (i.e. full title + ordinal identifier, instead of author/date + ordinal identifier)

**Comment by opoudjis** [comment]
Author/date implementation is pending https://github.com/metanorma/isodoc/issues/159
