### ISSUE TITLE
Support attributes for document type: Standard

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#12]
Source: https://github.com/metanorma/metanorma-ieee/issues/7
Add these attributes:
-  'developed by':
Example:
![image](https://user-images.githubusercontent.com/5559926/174097485-39eb9d1e-424b-4268-9275-3c68ff3682d6.png)

- 'parent' organization of 'developed by':
Example:
![image](https://user-images.githubusercontent.com/5559926/174098027-458e10ae-20c2-40ab-ac97-11df65e6f070.png)

Full example from PDF:
![image](https://user-images.githubusercontent.com/5559926/174098089-b52bdab8-6437-4b49-bb77-63cbf93669c6.png)

- 'approved date':
Example:
![image](https://user-images.githubusercontent.com/5559926/174098162-adbb68e4-c374-4615-b105-2709e7fc0391.png)

- 'approved by':
Example:
![image](https://user-images.githubusercontent.com/5559926/174098239-eabfaa9b-9a1d-42bd-bb2d-fe31b7c8fc82.png)

Full example from PDF:
![image](https://user-images.githubusercontent.com/5559926/174098295-4bcecdab-cad7-459f-abf2-64bb734b0172.png)

- 'revision' and 'incorporating':
![image](https://user-images.githubusercontent.com/5559926/174098645-7cdcc845-3b9f-41c9-9e1e-b4b03599a6dc.png)

- we have `:isbn:` already, but we need 2nd one for PDF or print:
![image](https://user-images.githubusercontent.com/5559926/174099073-cfaab943-c336-4e5b-b54e-93c21848473a.png)

- I don't know what is it, but need two fields related to ISBN
![image](https://user-images.githubusercontent.com/5559926/174099326-b29aecde-dac6-4171-8b75-5e0a3b09c3e8.png)

**Comment by opoudjis** [comment]
Refer https://github.com/metanorma/metanorma.org/pull/611:

`isbn-pdf`:: The ISBN of the PDF document.
`isbn-print`:: The ISBN of the print document.

`stdid-pdf`:: The final standard identifier of the PDF document.
`stdid-print`:: The final standard identifier of the print document.

realised as:

````
           <docidentifier type='IEEE' scope='PDF'>GHI</docidentifier>
           <docidentifier type='IEEE' scope='print'>JKL</docidentifier>
           <docidentifier type='ISBN' scope='PDF'>ABC</docidentifier>
           <docidentifier type='ISBN' scope='print'>DEF</docidentifier>
````

**Comment by opoudjis** [comment]
I've modelled the Developed By and its Parent as committee and society:

````
`society`:: The IEEE society responsible for the document. Do not include the "IEEE" prefix.
`committee`:: The committee responsible for the document.
`working-group`:: The working group responsible for the document.
`balloting-group`:: The Standards Association balloting group responsible for the document.
````

Rendered as:

````
            <ext>
              <doctype>standard</doctype>
              <editorialgroup>
                <society>SECRETARIAT</society>
                <balloting-group>SC</balloting-group>
                <working-group>WG</working-group>
                <working-group>WG1</working-group>
                <committee>TC</committee>
                <committee>TC1</committee>
              </editorialgroup>
````

Approved date and Approved By are:

`confirmed-date`:: The date on which the document was approved.

i.e. `<date type="confirmed">`

Currently, the Approved By is static text: "IEEE SA Standards Board". I have yet to get to the operations manual of the IEEE, because everyone involved in this venture is being profoundly impatient. If it turns out that approval bodies are changeable, I will add an attribute for it.

**Comment by opoudjis** [comment]
I have not yet modelled Revision and Incorporating, and they are going to have to WAIT until I get through the current DELUGE of tickets.

**Comment by opoudjis** [comment]
Well... I got to this more quickly than feared (but only by skipping https://github.com/metanorma/metanorma-ieee/issues/39 )

There is nowhere obvious to insert this information in the Word template (which looks completely different to the PDF, being oriented to drafts), so I am going to ignore this information in the Word document.

The "Revision of" points to the document this document updates; so, `:updates:`.

The "Incorporates" could be one of:

> includes
> document A includes document B, through a well-defined relation outlined in [Host item](https://www.relaton.org/specs/model/relations/#host-item), and with distinct metadata (including authorship) and bibliographic record (e.g. Chapter in Edited Work, Illustration) (includedIn)
> 
> hasPart
> document A includes document B, with no distinct metadata (other than extent) or bibliographic record, and all items in document B share the same authorship or corporate authorship (e.g. Chapter, Section, Part, Volume, Issue, Track) (partOf)
> 
> merges
> document A results from a merger of earlier documents B1, B2, B3…​ (mergedInto)

"Includes" is article and journal or paper and collected volume; it does not apply here, because the content is seamlessly integrated into the present content. "hasPart" also doesn't apply, because the prior documents are not distinct parts of this document. Therefore, this is `:merges:`.

**Comment by opoudjis** [comment]
The results in bibdata are:

````
    <relation type='merges'>
      <bibitem>
        <title>--</title>
        <docidentifier>BCD</docidentifier>
      </bibitem>
    </relation>
    <relation type='merges'>
      <bibitem>
        <title>--</title>
        <docidentifier>EFG</docidentifier>
      </bibitem>
    </relation>
    <relation type='updates'>
      <bibitem>
        <title>--</title>
        <docidentifier>ABC</docidentifier>
      </bibitem>
    </relation>
````

**Comment by Intelligent2013** [comment]
@opoudjis thank you!
