### ISSUE TITLE
Introduction and ToC divided in several columns

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#121]
In relation to https://github.com/metanorma/mn-samples-ieee-private/pull/11

Introduction and table of contents are getting divided in columns.
I suspect because of the influence of "Participants" section.

![issue2-1](https://user-images.githubusercontent.com/33627611/180653522-2f305449-62c7-415c-880a-b0833d144af4.PNG)

![issue2-2](https://user-images.githubusercontent.com/33627611/180653524-8be0a762-fbb8-40a0-9e59-6b4cb92226b7.PNG)

**Comment by opoudjis** [comment]
The count of sections in the Word template is currently fixed, and I'm going to need genuinely OVERWHELMING evidence of a need to make the  count of sections fluid.

**Comment by opoudjis** [comment]
https://github.com/metanorma/annotated-express/issues/97

I am very angry about this. I am going to have to make the section set-up fluid, and the sections are set up in CSS: it is going to be DIFFICULT to do this.

**Comment by ronaldtse** [comment]
Are you replying to a different ticket?

**Comment by opoudjis** [comment]
No, although that link wasn't the justification for this I thought at first it was. But fluidity in marking up content with columns, while feasible, is not desirable.

**Comment by ronaldtse** [comment]
I’m any case, this ticket is about a regression in the participants column configuration overflowing into main content, so it shouldn’t be controversial.

**Comment by opoudjis** [comment]
Section 9, at the end of the Standards Board, is meant to be a resumption of single column text, but was still marked up as 3 columns in the CSS. (We had not noticed before, because it contains the single "*Emeritus Member" paragraph normally.

That adjustment made, the document now looks normal. The day will still come when I need to introduce more flexibility in the CSS treatment of sections. Today is not that day.

I have to change the final paragraphs markup to center-aligned for each paragraph: it does not work with alignment indicated in an open block.
