### ISSUE TITLE
Add IEEE SA XML output format using mnconvert

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#132]
The conversion from Metanorma XML to IEEE xml available in mnconvert v1.20.0 (https://github.com/metanorma/mnconvert/releases/tag/v1.20.0).

How to convert from Metanorma XML (semantic) to IEEE XML:
```
java -jar mnconvert-1.20.0.jar document.xml --output-format ieee --validation-against C:\Metanorma\IEEE\standards-1-7-DTD\standards-1-7-dtd\standards.dtd
```

Latest documentation with mapping between IEEE XML and Metanorma adoc and XML: [IEEE_vs_NISO_and_MN_comparison_v.0.4.docx](https://github.com/metanorma/mnconvert/files/9331516/IEEE_vs_NISO_and_MN_comparison_v.0.4.docx)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mnconvert/issues/161#issuecomment-1214162506_

**Comment by opoudjis** [comment]
mnconvert-ruby does not know about ieee yet. Fixing.

**Comment by opoudjis** [comment]
Cannot find C:\Metanorma\IEEE\standards-1-7-DTD\standards-1-7-dtd\standards.dtd

This file needs to be included in the metanorma gem. I have added the validation-against option to the mnconvert-ruby gem. Someone is going to have to work out how to invoke validation-against with a relative directory path, because "C:\Metanorma\IEEE\standards-1-7-DTD\standards-1-7-dtd\standards.dtd" is not where that DTD is going to be located.

**Comment by opoudjis** [comment]
@Intelligent2013 Please provide the standards.dtd file in the mnconvert gem, I see there are a bunch of DTDs in there already

@CAMOBAP I can't run rspec, because the fixtures are gitignored out of them gem. I've uploaded what I have to date to mnconvert-ruby, but I request that you finish it off.

**Comment by Intelligent2013** [comment]
@opoudjis `C:\Metanorma\IEEE\standards-1-7-DTD\standards-1-7-dtd\standards.dtd` is just an example path. The user should specify the real absolute or relative path to the IEEE STL DTD.
Example for relative path:
`--validation-against .\ieee-stl\standards-1-7-DTD\standards-1-7-dtd\standards.dtd`

For validation against NISO/ISO DTD and XSD, I've added them into mnconvert.jar, because they can be downloaded freely on NISO site, but IEEE STS DTD standards.dtd can't be shared to free access, therefore I've added the new parameter `--validation-against`. In this case user should have own instance of IEEE STS DTD standards.dtd for the validation.

**Comment by Intelligent2013** [comment]
I'll turn off the validation if output-format is ieee, and DTD path isn't specified. Because the validation is not make sense in this case.

**Comment by opoudjis** [comment]
@CAMOBAP I need you to somehow get the rspec working here for 

````
it "converts XML to IEEE XML" do
    sts_path = Pathname.new(Dir.pwd) / "rice-en.cd.ieee.xml"

    MnConvert.convert(
      mn_xml,
      {
        output_file: sts_path,
        input_format: :metanorma,
        output_format: :ieee,
        debug: true,
        validation_against: "https://github.com/metanorma/ieee-stl/blob/main/standards-1-7-DTD/standards-1-7-dtd/standards.dtd",
      },
    )

    expect(sts_path.exist?).to be true
    expect(sts_path.read).to include '<preformat preformat-type="ruby">'
  end
````

"https://github.com/metanorma/ieee-stl/blob/main/standards-1-7-DTD/standards-1-7-dtd/standards.dtd" is where the DTD is online, but of course you will need to run it from a local copy.

**Comment by ronaldtse** [comment]
I can't find the 2015 IEEE XML DTD online and it is still considered private.

I have asked IEEE SA whether they are willing to share the DTD publicly, and will update.

For now, let's use GHA to pull the DTD for testing.

**Comment by ronaldtse** [comment]
Official answer from IEEE SA:

> We share our DTD with WGs, if there's a compelling reason to do so, but don't make it publicly available. 

The IEEE SA DTD cannot be shared publicly, so the current approach of pulling from our private repository remains.

For the RSpec that runs validation, we can use an environment variable to provide the path of the DTD, e.g.
```sh
IEEE_SA_DTD_PATH=~/src/ieee-stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd rake spec
```

**Comment by opoudjis** [comment]
Waiting on @CAMOBAP and https://github.com/metanorma/mnconvert-ruby/pull/12
