### ISSUE TITLE
IEEE XML mixed-citation fields semantic representation

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ieee#137]
Source issue: https://github.com/metanorma/mnconvert/issues/173

I'm converting IEEE XML mixed-citation sub-elements into Metanorma AsciiDoc with further Metanorma XML to IEEE XML conversion.

In IEEE SA XML samples there are a few elements which don't fit into https://www.metanorma.org/author/topics/document-format/bibliography/#annotating-pre-formatted-citations-semantically:
- `<gov>U.S. Environmental Protection Agency Hazardous Material Rules</gov>`
- `<month>Nov.</month>`
- `<article-title>Audible Noise Reduction</article-title>,&#x201d; <source>T &amp; D</source>` (two titles)
- ` <fpage>60</fpage><lpage>175</lpage>`
- `<conf-name>1995 IEEE/PES Winter Meeting</conf-name>`
- `<institution>U.S. EPA</institution>`

What is the best way to convert these data into AsciiDoc without loss semantic data?

In IEEE DTD there are more elements, so I can expand this list if need.

**Comment by Intelligent2013** [comment]
Source IEEE XML fragment:
```xml
<ref id="B1">
	<label>[B1]</label>
	<mixed-citation publication-format="print" publication-type="government">
		<article-title>Code of Federal Regulations Title 40 Part 260 (40CFR260)</article-title>, <gov>U.S. Environmental Protection Agency Hazardous	Material Rules</gov>.</mixed-citation>
	<xref ref-type="fn" rid="fn6">
		<sup>6</sup>
	</xref>
	<fn id="fn6">
		<label>
			<sup>6</sup>
		</label>
		<p>CFR publications are available from the U.S. Government Printing Office	(<uri>http://www.gpo.gov/</uri>).</p>
	</fn>
</ref>
...
<ref id="B13">
	<label>[B13]</label>
	<mixed-citation publication-format="print" publication-type="periodical">
		<person-group person-group-type="author">
			<string-name>
				<surname>Pedersen</surname>, <given-names>R. S.</given-names>
			</string-name>
		</person-group>, &#x201c;<article-title>Audible Noise Reduction</article-title>,&#x201d; <source>T &amp; D</source>,	<month>Nov.</month>
		<year>1976</year>.</mixed-citation>
</ref>
...
<ref id="B17">
	<label>[B17]</label>
	<mixed-citation publication-format="print" publication-type="periodical">
		<person-group person-group-type="author">
			<string-name>
				<surname>Schultz</surname>, <given-names>M.	W.</given-names>
			</string-name>, and <string-name>
				<surname>Ringlee</surname>,	<given-names>R. J.</given-names>
			</string-name>
		</person-group>,	&#x201c;<article-title>Some Characteristics of Audible Noise of Power Transformers
								and Their Relationship to Audibility Criteria and Noise
							Ordinances</article-title>,&#x201d; <source specific-use="IEEE">IEEE Transactions</source>, Paper <fpage>60</fpage>
		<lpage>175</lpage>,	<month>Feb.</month>
		<year>1960</year>.</mixed-citation>
</ref>
...
<ref id="B18">
	<label>[B18]</label>
	<mixed-citation publication-format="print" publication-type="confpaper">
		<person-group person-group-type="author">
			<string-name>
				<surname>Sebo</surname>,				<given-names>Stephen A.</given-names>
			</string-name>, and
										<string-name>
				<surname>Caldecott</surname>,	<given-names>Ross</given-names>
			</string-name>
		</person-group>,	&#x201c;<source>Substation Magnetic Field Management Techniques</source>,&#x201d; <publisher-name>Department of Electrical Engineering, The Ohio State University</publisher-name>, <publisher-loc>Columbus Ohio</publisher-loc>. Paper given at a Panel Session on EMF Management Techniques at the <conf-name>1995 IEEE/PES	Winter Meeting</conf-name>, <month>Feb.</month>
		<year>1995</year>.</mixed-citation>
</ref>
...
<ref id="B23">
	<label>[B23]</label>
	<mixed-citation publication-format="print" publication-type="report">
		<institution>U.S. EPA</institution>
		<source>2006 Annual Report, &#x201c;SF<sub>6</sub> Emission Reduction Partnership for	Electric Power Systems,&#x201d;</source>
		<month>Nov.</month>
		<year>2007</year>.</mixed-citation>
</ref>
```

**Comment by opoudjis** [comment]
In particular, JATS is doing some bizarre stuff differentiating `gov` and `source`, which frankly, I am having massive trouble understanding. 

It seems that `gov` is either the ID or the title of a report, but the report is not cited as an autonomous resource, but via inclusion in the `source`:

https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-cit0.html

````
<ref>
<element-citation publisher-type="gov">
<person-group person-group-type="author">
<name><surname>Norman</surname>
<given-names>John C</given-names></name>
<aff>Texas Heart Institute, Houston, TX</aff>
</person-group>
<gov>Report No.: NIH-N01-HV-5-3006-4-VI. Contract No.
N01-HV-5-3006</gov>
<source>ALVAD: 1980. A comprehensive final report to NHLI</source>
<volume>1</volume>
<publisher-loc>Bethesda (MD)</publisher-loc>
<publisher-name>National Institutes of Health, National Heart and Lung
Institute, Devices and Services Branch</publisher-name>
<month>01</month>
<year iso-8601-date="1980-01">1980</year>
<size units="page">340</size>
<comment>Available from: NTIS, Springfield, VA;
PB80-148810</comment>
</element-citation>
</ref>
````

_Report No.: NIH-N01-HV-5-3006-4-VI. Contract No. N01-HV-5-3006_ is the identifier of the report. But the cited resource is the source, _ALVAD: 1980. A comprehensive final report to NHLI_.

The conclusion I'm coming to is:

* If both `gov` and `source` are present in a resource, `source` is the title of the resource, and `gov` is the docidentifier of the source. It is a wordy messy identifier (in the example above, it's actually two identifiers), but that's not your problem.
* If `gov` is present and `source` is not, then `gov` is treated as the title of the resource.

So, in my span notation,

`span:type[techreport]`, unless there's overwhelming evidence otherwise (e.g. stuff that looks like it is a published volume)

`span:title[{source}.] span:docid[{gov}]`

**Comment by Intelligent2013** [comment]
> I also don't want to have to completely reimplement the bibliographic rendering of IEEE without adequate documentation.

The IEEE STL documentation available here:
https://github.com/metanorma/ieee-stl/tree/main/standards-1-7-HTML/standards-tag-library
(clone and open locally)

NISO STS also has very similar structure of mixed-citation:
https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/element/mixed-citation.html

**Comment by opoudjis** [comment]
`month` and `year` are differentiated in JATS, because JATS is a presentation-oriented format. We will not do that: we will instead incorporate month and year into the one date.

It is true that right now, *I do not extract months out from the year for publication* in relaton-render. So when I try to render such citations, I will have a problem. I'll deal with that when it happens.

So 

bibitem/date = {year}-{month} (in ISO format), meaning to convert the month into a two-digit number. We're going to have semantic citation data: we can't have random month names in there.

In span notation, `span:pubyear[{year}-{month}]`. Don't worry about the fact that I called it pubyear.

**Comment by opoudjis** [comment]
> > I also don't want to have to completely reimplement the bibliographic rendering of IEEE without adequate documentation.
> 
> The IEEE STL documentation available here: https://github.com/metanorma/ieee-stl/tree/main/standards-1-7-HTML/standards-tag-library (clone and open locally)
> 
> NISO STS also has very similar structure of mixed-citation: https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/element/mixed-citation.html

Thank you, I found JATS after I wrote that, https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-m3n0.html, and I am going to take that as the source (I understand STL is a profile of JATS).

**Comment by opoudjis** [comment]
`article-title` and `source` being differentiated: Turns out, that's the normal process for journal publications: `source` is the journal title.

We can deal with that fine in Relaton XML:

````
bibitem/@type = article
bibitem/title = {article-title}
bibitem/series/title = {source}
````

Right now, I do not have a span notation for journal titles. I can introduce one, but I'm reluctant to overload the notation, would want to discuss with @ronaldtse 

The alternative is raw Relaton XML, or AsciiBib.

**Comment by opoudjis** [comment]
`fpage` and `lpage` are the start and end page number of an article or chapter. We encoded that in Relaton as extent:

````
bibitem/extent = 
<extent>
  <locality type="page">
    <referenceFrom>{fpage}</referenceFrom>
    <referenceTo>{lpage}</referenceTo>
  </locality>
</extent>
````

Not currently catered for in span notation. Again, reluctant to get too deep with span notation; if I do get into pages, I'm not sure I'd also want to get into other kinds of extent.

**Comment by opoudjis** [comment]
`conf-name` is the name of the conference that a presentation is given in. 

Which we have not modelled in relaton. We've modelled it in ISO 690, so the modelling construct is there, but I haven't had to deal with it to date, so I haven't had to serialise it to relaton yet. I think the most expedient thing to do is to make the conference title a series title --- a conference can be thought of as a series of presentations. I'd have to think about whether to make the institution a place, or a publisher.

**Comment by opoudjis** [comment]
> Even we'll find Metanorma XML tags for each mixed-citation element, then the big task/problem for me is backward conversion - building `<mixed-citation>` from set of Metanorma XML tags in Metanorma XML to IEEE XML. Metanorma XML is the set of semantic elements, but mixed-citation is the sequence of element for presentation.

That isn't as bad as you think. Presentation XML uses relaton-render to convert semantic citations into renderable citations. The `<formattedref>` element is thus generated to look like the mixed-citation of your target. We would have to preserve the markup of the elements in the IEEE instance of relaton-render, but we are already doing that for metanorma-iso, by using span in the output.

But I want to be explicit here. You're stumbling on a MAJOR project here, of mapping between two citation formats that are not 1:1 equivalent, that will likely not have been marked up well, covering domains such as conferences that we have not ever generated a citation in before. This is not a couple of days' work. JATS is a huge tagset, so is Relaton, and this would be forcing Relaton to expand massively.

If this is responding to a genuine current need of IEEE, then we're going to have to schedule it and resource it.

If this is being driven by sample documents, so that eventually, potentially, someone might use it down the road, then it is simply going to have to be deferred. We have tickets that have been unactioned for years, and we have current clients with pressing needs. We don't have the luxury of initiating new bibliographic encoding projects without a committed user. And even so, this is work that is going to have  to be scoped and scheduled. I cannot implement the five bibliographic tags of JATS you've encountered in this set of sample documents, in isolation from the rest of bibliographic JATS.

@ronaldtse over to you.

**Comment by opoudjis** [comment]
We've discussed; this does not need to be actioned, you can leave them as formattedref.

https://github.com/metanorma/metanorma-standoc/issues/668 will add a few more spans, which will address the requirements found here, but you don't need to use them.
