### ISSUE TITLE
Generated order wrong in IEEE documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#149]
See https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/11

**Comment by opoudjis** [comment]
We require there to be only one Overview clause, but are relying on the clauses to appear in the right order in the Semantic XML, to identify it. Relaxing that constraint: it is the first occurring Overview clause, not the first clause.

The problem arose because markup inserted Introduction before the Overview, as a main section clause. We do not allow that.

If the Introduction is intended as a preface clause, it should be marked up as `[preface]`. It is not accepted as such by default, because Introduction is not foreseen as a preface clause by the IEEE editorial guide.

**Comment by ronaldtse** [comment]
As I posted here: https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/11#issuecomment-1276454883

> The problem arose because markup inserted Introduction before the Overview, as a main section clause. We do not allow that.
> 
> If the Introduction is intended as a preface clause, it should be marked up as `[preface]`. It is not accepted as such by default, because Introduction is not foreseen as a preface clause by the IEEE editorial guide.

@opoudjis: 

1. The order of placing the "Introduction" content before "Overview" content was always the case. This is clearly a regression.
2. The "Introduction" should not require any `[preface]` label (we never had this until it broke). Every IEEE SA document requires presence of an "Introduction". Just like in ISO, there is no need to label the Introduction even though it is not a main content clause. 

The assumptions of the fix are incorrect. I am not sure whether this bug has been truly fixed.

**Comment by ronaldtse** [comment]
Reopening until both 1 and 2 are verified.

**Comment by opoudjis** [comment]
Yes, there was a refactor in how start of section is detected. Fixed.

<img width="1333" alt="Στιγμιότυπο 2022-10-13, 21 49 15" src="https://user-images.githubusercontent.com/1911039/195577663-7e8df6c4-ee40-446e-ad4a-86a515a07142.png">
