### ISSUE TITLE
Citation with bibliographic spans for surname and initials crash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#173]
There are these two entries in:
* https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/blob/rplews_terms_work/sources/ieee-p2874/sections/aa-bibliography.adoc

Somehow, the first bibitem here works fine.

The second, causes a crash:

```adoc
* [[[edge_mesh,1]]],
span:initials[Y.] span:surname[Sahni], span:initials[J.] span:surname[Cao], span:initials[S.] span:surname[Zhang], and span:initials[L.] span:surname[Yang],
span:title[Edge Mesh: A New Paradigm to Enable Distributed Intelligence in Internet of Things].
span:type[inproceedings]
In: span:in_title[IEEE Access],
vol. span:volume[5],
pp. span:pages[16441-16458],
span:date[2017],
doi: span:uri.doi[10.1109/ACCESS.2017.2739804].

* [[[ferre-bigorra,1]]],
span:initials[J.] span:surname[Ferré-Bigorra], span:initials[M.] span:surname:[Casals], span:initials[G.] span:surname[Gangolells],
span:title[The adoption of urban digital twins].
span:type[inproceedings]
In: span:in_title[Cities].
vol. span:volume[131],
pp. span:page[103905],
span:date[2022].
doi: span:uri.doi[10.1016/j.cities.2022.103905].
```

Crash with the second entry:
```
{:completename=>nil, :surname=>nil, :initials=>#<RelatonBib::LocalizedString:0x0000000123d5e8e0 @language=nil, @script=nil, @content="M.">, :forename=>[], :addition=>[], :prefix=>[]}
Should be given :surname or :completename
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/full_name.rb:36:in `initialize'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:303:in `new'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:303:in `get_person'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:362:in `block in fetch_contributors'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:360:in `map'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:360:in `fetch_contributors'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:35:in `item_data'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-bib-1.13.9/lib/relaton_bib/xml_parser.rb:11:in `from_xml'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:163:in `block in sanitise_citations_input_string'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:162:in `each_with_object'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:162:in `sanitise_citations_input_string'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:155:in `sanitise_citations_input'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.2/lib/relaton/render/general/render.rb:148:in `render_all'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.1/lib/isodoc/presentation_function/refs.rb:25:in `references_render'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-0.0.7/lib/isodoc/ieee/presentation_ref.rb:46:in `references_render'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.1/lib/isodoc/presentation_function/refs.rb:7:in `references'
```

From the 2nd entry, when I remove the line with `span:initials` and `span:surname`, it works.

There is somehow an issue in the initials/surname ordering (I suspect) that crashes relaton-render. (Even though the structure is nearly identical to the first bibitem).

**Comment by ronaldtse** [comment]
@ReesePlews just found the problem, it was a syntax mistake:
```
span:surname:[Casals]
```

There is an extra colon after `span:surname`.

The main problem here is that if there is no surname, it should probably not crash?

**Comment by ronaldtse** [comment]
This situation happens very often, such as:

```adoc
span:initials[A.], span:surname[Deguchi], span:initials[et al.],
```

Which will crash, because et al is not an initial.

We need to find a way so that users know they need to provide initials WITH surname. Or better yet, provide them in the same brackets. The method now makes it too easy to crash.

**Comment by opoudjis** [comment]
Illegal syntax like 

> There is an extra colon after span:surname.

I can do nothing about, it's down to the Asciidoctor parser.

One thing I can do is crash out early, before passing data to relaton for parsing, if the span is missing needed data.

I am disinclined to make the spans syntax some baroque clumsy omnishamble of including the kitchen sink, which is where a lot of Metanorma "just add this markup option" proposals end up. I could add a `name:[]` macro, which has an extremely restrictive syntax of 

````
span:name[{(frontnames+)\ssurname]

frontnames = frontname | frontname \s+ frontnames
frontname = \S+

surname = \S+
````

With the postprocessing that if all frontnames end in full stop, they will be processed as formatted initials, and if any do not, they will all be processed as given names.

e.g. 

* `span:name[A. D. Hope]` (processed as one set of initials)
* `span:name[Alexander D. Hope]` (processed as two given names)
* `span:name[J. Edgar Hoover]` (processed as two given names)

If I do implement that, I will not permit ANY (**ANY**) deviation from that syntax, for any snowflake special case. Parsing these is difficult enough already. If you want a surname with a space in it, use the surname markup.

So the following will be REJECTED. This macro is a convenience macro to begin with:

* `span:name[A D Hope]` (You refuse to abide by span:name syntax? You get what you deserve. Given names.)
* `span:name[A D Navarro Cortez]` (You use the span:name syntax instead of explictly using span:surname for multi-word surnames? You get what you deserve: Navarro becomes a given name. I am not a clairvoyant, of course I'm going to use a default.)
 
By the way, this no longer counts as urgent, since it was not a Metanorma bug.

@ronaldtse For approval.

**Comment by opoudjis** [comment]
I'll call the span `span:fullname[]`

**Comment by ReesePlews** [comment]
@opoudjis thank you for adding this. could this new span also be used for an "et. al" case or would that be a different matter?

**Comment by ronaldtse** [comment]
The “et al” part should appear based on two criteria:
- there are too many authors (as per @opoudjis , over 7 authors in Chicago which is what IEEE states)
- The bibliographic item says et al. Which requires explicit encoding. 

For most of the encoding issues, we will implement DOI autofetch which should resolve most. 

For the software behavior, we will need to create the syntax so it will come later.

**Comment by opoudjis** [comment]
@ReesePlews "et al" is a completely different matter, and it would be an unacceptable abuse of the notation to add it here.

Our rendering of bibliographies is governed by the SDO stylesheet (as implemented in relaton-render), and it will only do "et al.", automatically, if (a) there are more authors involved than the "et al." limit set by the SDO, and (b) the SDO stylesheet we have implemented provides for "et al." at all.

We have not to date implemented et al. for IEEE, because the IEEE SA Style manual does not explicitly say that they have an "et al." threshold for author names. They do however defer to the Chicago Manual of Style, and the example given at 12.3.7 uses et al. after the first 7 names.

CMS in fact, I find, have a rule I find silly:

> Journal articles often list many authors, especially in the sciences. If there are four or more authors, list up to ten in the reference list; in the text, list only the first, followed by et al. (“and others”). For more than ten authors (not shown here), list the first seven in the reference list, followed by et al.

I have not implemented this kind of folderol with numbers, because I followed a more straightforward approach: if more than N authors, print the first N authors, then et al. I now have to implement "if more than N, print the first M authors." That is going to have to be a separate ticket, and given that I have over 100 tickets backlog, I will need explicit guidance from you on when you would need it implemented.

But the take-away is, the way to enter et al. is to explicitly add ALL the authors (or at least, enough authors to trigger CMS's threshold in this case.) Metanorma starts with semantic markup, and is explicitly meant to provide reusable resources: if a document is recompiled for another SDO, with a higher or no threshold for et al., we need to be able to satisfy it.

As @ronaldtse has indicated, we will be implementing DOI autofetch which will reduce much of the effort around entering authors.

**Comment by ReesePlews** [comment]
@opoudjis and @ronaldtse  thank you for the message. presently there is only one et al. notation in the project bibliography, i will add seven of the authors and leave off the last person.  in the future i can come back to this, it is not important at this time.  i have only been referring to clause 19 in the ieee style manual.  there is no et al. rules mentioned there.  the CMS is referenced in the ieee style manual. i assumed that my bib.adoc file was being rendered through metanorma based on the sdo flavor. if that is incorrect, i will refer to the CMS or output from zotero to check the entries.  sorry to bother you guys with too many questions.

**Comment by opoudjis** [comment]
Not at all. The bib.adoc is being rendered through the SDO flavour, it's just that (until now!) I had not noticed how et al. was handled by IEEE, because I did not look up CMS. If you can find all the authors, please add 10, so that when I implement the et al. rule, we get the right results.

I'm implementing `fullname:[]` in the next few hours...

**Comment by opoudjis** [comment]
... for liberal notions of "next few hours" lol.

**Comment by opoudjis** [comment]
Allow multiple given names. Allow mononyms, surname-only.

**Comment by opoudjis** [comment]
Functionality will be available in release scheduled for December 5.
