### ISSUE TITLE
Citations with titles not showing author/org and URL

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#174]
Source:

```adoc
* [[[ethicalgeo,1]]],
span:organization[American Geographical Society].
span:title[The Locus Charter]. span:date[2022].
Available at: span:uri[https://ethicalgeo.org/locus-charter/]
```

Rendering:
<img width="258" alt="Screen Shot 2022-11-13 at 7 15 08 PM" src="https://user-images.githubusercontent.com/11865/201518854-646dd9ff-efb6-4af8-b2f9-49be0660c223.png">

Doc:
* https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/tree/rplews_terms_work

**Comment by ronaldtse** [comment]
@opoudjis I understand. Follow up questions:
1. The error in relaton-bib was a missing "type". If the default bibliographic type was "standard", why is there a missing "type"?
2. Does the default bibliographic type of "standard" makes sense? We should at least issue a warning when the bibliographic type is not set.

**Comment by opoudjis** [comment]
1. There is no missing type: the type of "standard" was supplied by Metanorma, and that resulted in only the title being displayed.
2. Be careful what you wish for. To date, almost all our citations have been standards, which is why the default is the only obvious one. I can issue warning for missing type in citations marked up with spans, I guess, but nobody's paying attention to the warnings as is.
