### ISSUE TITLE
Source code rendering should not generate slanted quotes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#191]
Source code should not generate slanted quotes.

Source:
```adoc
[source,json]
----
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.org/some-definitions-schema.json",
  "$defs": {
    "Class1": {
      "type": "object",
      "properties": {
        "prop1": {"type": "string"}
      },
      "required": ["prop1"]
    },
    "Class2": {
      "type": "object",
      "properties": {
        "prop2": {"type": "number"}
      },
      "required": ["prop2"]
    }
  }
}
----
```
<img width="858" alt="Screen Shot 2022-12-01 at 8 35 16 PM" src="https://user-images.githubusercontent.com/11865/205054431-d941f179-7445-49fa-909c-85b1fa71da18.png">

**Comment by opoudjis** [comment]
I cannot replicate this, and there is code explicitly in place to prevent this happening:

````
= Empty
Empty
:docnumber: 1000
:no-pdf:

== Clause

[source,json]
----
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.org/some-definitions-schema.json",
  "$defs": {
    "Class1": {
      "type": "object",
      "properties": {
        "prop1": {"type": "string"}
      },
      "required": ["prop1"]
    },
    "Class2": {
      "type": "object",
      "properties": {
        "prop2": {"type": "number"}
      },
      "required": ["prop2"]
    }
  }
}
----
````

is compiling in IEEE to:

````
<pre id="_3c23d23c-ab1d-267c-48ff-7f7e08cf4ff7" class="prettyprint ">{<br />&#xA0; "$schema": "http://json-schema.org/draft/2019-09/schema",<br />&#xA0; "$id": "http://example.org/some-definitions-schema.json",<br />&#xA0; "$defs": {<br />&#xA0;&#xA0;&#xA0; "Class1": {<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "type": "object",<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "properties": {<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "prop1": {"type": "string"}<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; },<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "required": ["prop1"]<br />&#xA0;&#xA0;&#xA0; },<br />&#xA0;&#xA0;&#xA0; "Class2": {<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "type": "object",<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "properties": {<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "prop2": {"type": "number"}<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; },<br />&#xA0;&#xA0;&#xA0;&#xA0;&#xA0; "required": ["prop2"]<br />&#xA0;&#xA0;&#xA0; }<br />&#xA0; }<br />}</pre>
````

No smart quotes.

Kindly provide more data to enable replication. This is not currently a valid ticket.

**Comment by ronaldtse** [comment]
This also happens with OGC, I saw that just last week. This is a Metanorma wide issue. I will verify and provide a document with this issue.

**Comment by ronaldtse** [comment]
And when you close this please provide a screenshot.

**Comment by opoudjis** [comment]
The issue was triggered because of captions.

````
[#example_jsonschema_definitions_schema,reftext='{listing-caption} {counter:listing-num}']
.JSON Schema example of a definitions schema
[source,json,linenumbers]
----
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "Class1": {
      "type": "object",
      "properties": {
        "prop1": {"type": "string"}
      },
      "required": ["prop1"]
    },
    "Class2": {
      "type": "object",
      "properties": {
        "prop2": {"type": "number"}
      },
      "required": ["prop2"]
    }
  }
}
----
````

and you saw fit to omit the caption in your code snippet.

When you fail to provide me complete documents to test on, and randomly leave critical parts of the test data out, you save 10 seconds, and **you waste an hour of my time and yours** as I try to find out what actually happened.

I am strongly inclined to reject all tickets that do not link to a complete document for replication.

Your screenshot:

<img width="953" alt="Στιγμιότυπο 2022-12-14, 22 09 41" src="https://user-images.githubusercontent.com/1911039/207580128-a5f5f339-c73f-4463-8699-9e90e3c97d50.png">

**Comment by ronaldtse** [comment]
> The issue was triggered because of captions.

The fix was implemented as per https://github.com/metanorma/metanorma-ogc/issues/476#issuecomment-1350929755 . 

> and you saw fit to omit the caption in your code snippet.

The caption issue was irrelevant. I actually copied out the exact code shown to an IEEE document to generate the provided screenshot. Nothing was missing from the ticket. It was a bug.

**Comment by opoudjis** [comment]
A bug I could not replicate with the limited context you provided. It was therefore a useless ticket.

The bug was triggered by captions, because captions resulted in there being more than one child of the sourcecode node. By not providing me the full context, you made it impossible for me to replicate the bug. It was only when I recovered the full context that I did fix it.

The caption issue was NOT irrelevant, and the fix says EXPLICITLY "This issue arises when sourcecode is captioned." Your claim that "the caption issue was irrelevant" **is false**.

I am asking you to change bug reporting behaviour, by providing bug reports ONLY in connection with a complete document.

If you continue to refuse to do so, and I cannot replicate the error with the context you provide, then I will be continue to  decline to action the ticket any further, until you do provide a full document as context.

I am not a clairvoyant, I am very busy, and in this instance, I am completely right. What exactly is the alternative? That I continue to stare at the ticket blankly? Is that going to replicate the error?
