### ISSUE TITLE
differences in line spacing between list multi-line entry and similar list from IEEE Style Guide

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/metanorma-ieee#292]
hello, i am finding a difference in spacing of multi-line list entries in ieee metanorma which is different from that of the IEEE style guide;
since trying to describe in text is not so clear, please see the images below:

IEEE Metanoma (exact document style with place-holder text inserted)  pink lines in the list are where there is too much space; the space between mulit-line entries in a list should be tighter, like a regular paragraph line height i think...

![20230731_ieee_metanorma_issue_with_text_spacing_in_list_raw](https://github.com/metanorma/metanorma-ieee/assets/35089343/5a38a3e1-6b3a-4ef3-aef8-b5be97013436)

IEEE Style Guide (small example) but clearly shows something different; (last entry in the list)

![20230731_ieee_metanorma_issue_with_text_spacing_in_list_IEEE_style_guide](https://github.com/metanorma/metanorma-ieee/assets/35089343/7ace1407-cd9d-4ca5-99d7-534a92278ae1)

i dont know the IEEE Metanorma version; this is being used in an IEEE P2784 project; the software, in my understanding, updates automatically when a new release is made.

thank you for looking into this;

**Comment by opoudjis** [comment]
So, in the current stylesheet, first level lists have 18pt spacing, and second level lists have 0pt spacing.

That 18pt spacing is derived directly from the IEEE-supplied Word template, IEEESTD-WORDTEMPLATE_v1_2022.doc, applied to the style "IEEEStds Unordered List".



There is no statement in the Style Manual about the line spacing of lists. The Word template supplied by IEEE, on the other hand, is **normative**, and it *explicitly* defines unordered lists as being spaced as I have it, rather than as the Style Manual illustrates it. Metanorma has it that way, because IEEE's Word template has it that way.

Therefore, I will not be actioning this ticket absent explicit guidance that I should from IEEE editorial.

**Comment by ReesePlews** [comment]
hello @opoudjis thank you for checking into this. i accept your stance on the matter. if we receive any comment from the IEEE editorial team related to this, i will pass it along.  i will make sure to close any items about this if they outside of this repo.  sorry to have taken your time with this, but thank you for checking.
