### ISSUE TITLE
(URGENT) PDF: missing Title and Author setting in IEEE document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#32]
From @cperey at https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/issues/60

> The PDF is being generated in the GitHub Job without a file name. So, when one opens it in a PDF reader, the name field is blank.
> 
> Can the document (file) name be given in the document.adoc file?

<img width="366" alt="Screenshot 2022-06-22 at 1 20 51 AM" src="https://user-images.githubusercontent.com/11865/174849068-df716f1f-623a-4469-985e-e2dc55c71a15.png">

For title, we set to the full title (intro + main + part).

For author, we set to the IEEE standards committee.

**Comment by Intelligent2013** [comment]
So I have to add such new logic.

**Comment by ronaldtse** [comment]
> For the metadata 'title', by default. xslt reads the element title with current language and `type='main'`:
> 
> ```
> <xsl:value-of select="*[local-name() = 'title'][@language = $lang and @type = 'main']"/>
> ```
> 
> but IEEE presentation xml doesn't contain `@type` and contains `main-en` in `language`:
> 
> ```
> <title language="main-en" format="text/plain">Spatial Web Protocol, Architecture and Governance</title>
> ```

I think @opoudjis has to answer this?

**Comment by Intelligent2013** [comment]
Looks like I have to remove 'Abstract' (from `abstract/title`) at starts of Subject also:
![image](https://user-images.githubusercontent.com/5559926/174859674-27cb5e13-c3c0-46fd-a042-f11bfe449107.png)

**Comment by cperey** [comment]
@ronaldtse Thank you for getting your team involved!

Note the second title (beginning “Integrated application…blah blah” appears in title. I don’t know the origin of the part name but we do not currently have a part name so it has been removed from the document.adoc in the open PR.

**Comment by Intelligent2013** [comment]
Xslt updated.

**Comment by opoudjis** [comment]
OK...

This document was originally created as an ISO document. ISO supports intro, main, part titles.

This document is now being processed in metanorma-ieee, and metanorma-ieee is not metanorma-iso. Therefore, I am dropping attributes of ISO that, as far as the documentation provided to me indicates, have nothing to do with IEEE.

Metanorma requires rigorous modelling of titles, and it expects adherence to templates. I simply have not modelled bipartite or tripartite titles, as I have not yet seen anything in the IEEE Style Manual justifying them. There is only one title recognised in what I am doing, the attribute value of :doctitle:. 

Whatever the provenance of `language="intro-en"` is, it is a bug, and to be ignored. Since I have not even finished going through the IEEE Style manual yet in implementation, I advise people be patient with waiting for fixes. I have easily two more weeks of work to do.

If bipartite titles are a thing in IEEE, I require (a) guidance on how to render them, since they are not provided for in the IEEE template, and (b) some statement as to what the status of such title components are. Is this a sub-title? An alternative title?

I'm taking over this ticket, because clearly the treatment of bipartite titles is going to have to made explicit for IEEE. Until then, I am treating them as unsupported.

**Comment by ronaldtse** [comment]
@opoudjis I think IEEE standards only have one title.

**Comment by opoudjis** [comment]
This has not been resolved from correspondence with IEEE, who also think standards only have one title. The actual solution is to make the document attribute contain the full title, complete with em-dash.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/commit/cbf66032ddafca3dbccab3325a5eb8c98c79d211 was a mistake.

This document only has one title. The other additional title part was a mistake from our editors.
