### ISSUE TITLE
(URGENT) "IEV" the IEC Electropedia is not rendered in the bibliography when explicitly cited/used

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#337]
From https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/30

The official way to cite IEV:

```
=== instant

point on the {{time axis}}

NOTE: An instantaneous event occurs at a specific instant.

[.source]
<<ievtermbank,clause "113-01-08">>

....

[bibliography]
== Normative References
* [[[ievtermbank,IEV]]]
```

https://www.metanorma.org/author/topics/document-format/section-terms/

<img width="709" alt="Screenshot 2024-02-08 at 5 56 40 PM" src="https://github.com/metanorma/metanorma-ieee/assets/11865/a5850994-83f1-4c65-8bd6-513ac68e9174">

However, the "IEC Electopedia" entry is not displayed in an IEEE bibliography.

This code:
```adoc
* [[[iev,IEC Electropedia]]],

* [[[ievtermbank,IEC Electropedia]]],

* [[[ievterms,IEV]]]
```

Renders as:

![image](https://github.com/metanorma/metanorma-ieee/assets/11865/0bfa17c5-cf75-4595-b14d-e26db680fa04)

Notice that the last "properly encoded" item is omitted.

This is likely because in ISO/IEC the IEV does not need to be rendered. However, all other SDOs need it rendered specifically. And by citing we need to cite the correct "IEC 60050-XXX" part.

**Comment by opoudjis** [comment]
I am not getting this behaviour on standalone document.

![Screenshot 2024-02-09 at 00 00 59](https://github.com/metanorma/metanorma-ieee/assets/1911039/bfdb3e75-95ff-43fa-aff7-c633d45cfee8)

Looking at source document.

**Comment by opoudjis** [comment]
````
[relaton-iec] (IEC Electropedia) Fetching from Relaton repsitory ...
[relaton-iec] (IEC Electropedia) Not found.
[relaton-iec] (IEC Electropedia) TIP: If you wish to cite all document parts for the reference, use `IEC Electropedia (all parts)`.
[relaton-iec] (IEC Electropedia) Fetching from Relaton repsitory ...
[relaton-iec] (IEC Electropedia) Not found.
[relaton-iec] (IEC Electropedia) TIP: If you wish to cite all document parts for the reference, use `IEC Electropedia (all parts)`.
````

There is no such thing as 

````
* [[[iev,IEC Electropedia]]],

* [[[ievtermbank,IEC Electropedia]]],
````

The only valid reference is `* [[[ievterms,IEV]]]`. That is correctly rendering in a standalone document.

**Comment by opoudjis** [comment]
The  issue is user error. Error on the part of @ronaldtse misunderstanding what the actual problem was, and error from the document editors in entering a non-existent reference.

The reference was given in the document as:

````
[.source]
<<ievterms,clause=02-03-19>>, Note 1 has been modified. Note 2 has been added.
````

That means that the term is expected to live in ISO 60050-02, Clause 03-19.

There is No. Such. Document.

````
[relaton-iec] (IEC 60050-02) Fetching from Relaton repsitory ...
[relaton-iec] (IEC 60050-02) Not found.
[relaton-iec] (IEC 60050-02) TIP: If it cannot be found, the document may no longer be published in parts.
````

If you substitute the document with what is presumably the correct reference,

````
[.source]
<<ievterms,clause=102-03-19>>, Note 1 has been modified. Note 2 has been added.
````

then the bibliography renders fine:

![Screenshot 2024-02-09 at 00 18 56](https://github.com/metanorma/metanorma-ieee/assets/1911039/18b5eedd-bfd3-43ad-99de-228c7612a0a8)

**Comment by opoudjis** [comment]
A bogus reference like that will fail to be retrieved and populated in the bibliography. Such a case needs to result in aborting execution, which is the only way users will realise they have made an error, as they clearly aren't reading the error messages...

**Comment by ReesePlews** [comment]
@opoudjis thank you very much for examining this issue again.  i cannot try it at this time but i will update the 

> The only valid reference is * [[[ievterms,IEV]]]. That is correctly rendering in a standalone document.

in my document in the next edit cycle. i will report back to this issue when i can get it to work.

this issue:

> <<ievterms,clause=02-03-19>>, Note 1 has been modified. Note 2 has been added.

is my mistake. i am not using ISO 60050 only the online site and i have mistyped the part, it should be 102 as you have indicated.

i do check the error log but it is sometimes difficult to match the error with the entry.  if the generate actually failed to build, that would make checking the errors/warnings a more paramount task.

i will report back on my updates and be aware of the next update with the new commit _"Abort execution if non-existing IEV reference supplied"._ 

thank you again for checking this and finding my mistakes.

**Comment by ReesePlews** [comment]
hello @opoudjis today i have [made a check](https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/7842637112) of the rendering of the IEV reference.

as you described above, i have two references, one in clause 3 and one in the bibliography. (Note: these rendered images are from the PDF, i have not checked the word file.)

in using the iev reference, i expected the following:
a) in the bibliography i was thinking "ievterms" referred to the online electropedia only, and that my bib entry would be for the entire "electropedia" not just a specific clause. 
so with this code ` * [[[ievterms,IEV]]] ` i was not expecting to see this render in the bibliography:

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/8c0e6c96-f6e5-4c7f-9fe4-2da96b7237bf)

in the bibliography ievterms entry i did not specify a specific 60050 clause. it seems the IEV clause was picked up from this source reference entry code in clause 3:
```
[.source]
<<ievterms,clause=102-03-19>>, Note 1 has been modified. Note 2 has been added.
```
and this code in clause 3 in my document renders as:

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/3b42a945-9a46-4e93-89a8-12dad419eb61)

which seems to be an error or incorrect render in my document.

b) when used in clause 3, i would have expected a different kind of reference, not what you have shown above, however since it is referring to IEC 65050 which is "mult-part" then i guess it is ok, but i dont know why the source reference in clause 3 influences the bib entry to specifically be the reference clause and not just the main document. i can understand why the user may want separate bib entries for each part of the 60050 document, but in the bib code, i would have expected a different syntax to designate the part.

if only wanted a reference to the entire electropedia is that possible or because the document is multi-part is a citation always expecting a part?  i know i can create an entry manually for the "online electropeida" and that did render as i expected for the bib reference (but was not really an official reference), but that manual reference does not work for the clause 3 source reference. this is expected and would not be considered an issue.

c) additionally in the test i made today, the bibliography entry is out of order and renders like this:

![image](https://github.com/metanorma/metanorma-ieee/assets/35089343/c227ee9a-1626-439b-957d-0b36baee5a09)

d) when i first added this bib reference i used `ievtermbank`. which i found in the metanorma docs here: 
https://www.metanorma.org/author/topics/document-format/section-terms/

however the correct `ievterms` is additionally shown on another page here:
https://www.metanorma.org/author/topics/building/reference-lookup/

i am using google to find those documentation instances because the metanorma search bar does not seem to be working.

e) question: when the document is generated do all of the bib entry searches/fetches show up in the "metanorma generate site"? i cannot find a log entry to 60050 or some other entries. i think it would help if every search/fetch had a log entry.

based on the correct code you provided, i believe my document matches those sections. 

instead of opening a new issue, i have added my test results here. i will let you and @ronaldtse discuss and decide if anything from this comment should become a new issue(s) or not.

thank you for all the great work you are doing on this.
