### ISSUE TITLE
Support document type: IEEE SA Whitepaper

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ieee#4]
Template: [IEEE-SA_White_Paper_Template.docx](https://github.com/metanorma/metanorma-ieee/files/8901412/IEEE-SA_White_Paper_Template.docx)

Style manual: [IEEE-SA-Non_Standard_Projects_Style_Manual.pdf](https://github.com/metanorma/metanorma-ieee/files/8901439/IEEE-SA-Non_Standard_Projects_Style_Manual.pdf)

**Comment by opoudjis** [comment]
This is a template that honest-to-god has this in it:

<img width="755" alt="Screenshot 2023-08-31 at 18 58 01" src="https://github.com/metanorma/metanorma-ieee/assets/1911039/4aec7bf9-0f21-411b-b467-7927d97b70b8">

**Comment by ronaldtse** [comment]
We can certainly use other methods to implement the blue line...

**Comment by opoudjis** [comment]
> We can certainly use other methods to implement the blue line...

No we cannot, Ronald. IEEE are going to expect this document to be identical to their template, and are going to have kittens if they find out the blue line is something unfamiliar.

White paper styling is completely different from their standards, I am stuck having to implement this, this ticket has been delayed by a year, and this is functionality that I have no confidence will ever even be used.

**Comment by opoudjis** [comment]
Going to have lookup table of styles, to avoid rewriting methods between standards and white papers.

**Comment by opoudjis** [comment]
`<v:rect id="Rectangle_x0020_59"` is being converted to `<v:rect >...<a id="Rectangle_x0020_59"/>`. That is making textboxes horizontal instead of vertical; need to suppress that substitution within `<v:rect>`

**Comment by opoudjis** [comment]
The culprit ended up being `<v:textbox inset="0,,0">`: unfortunately it seems MHT export is exporting faulty Word HTML. Emending this to `<v:textbox inset="0,0,0,0"/>` works fine.

Add v:line to v:rect for preserving `@id`.

**Comment by opoudjis** [comment]
The disorderliness of the IEEE White Paper is awful, and needs to be brought to the attention of IEEE: it is an impediment to maintainability for themselves.

Quite apart from 

* the multiple random inconsistencies with the normal template, 
* the constant use of 0cm margin inline instead of in the style definition (which is begging with big pleading eyes for someone to forget to set it manually), 
* and the rather absurd expectation that authors will manually drag the blue bar under the abstract title (something  as easy to fix their side as making the blue bar positioned relative to the PARAGRAPH of the title),

if you try to regenerate the table of contents for a white paper, it *overflows into the sidebar*.

![Screenshot 2023-10-07 at 14 24 03](https://github.com/metanorma/metanorma-ieee/assets/1911039/7b0cb834-cfa2-4609-bccd-4d53551308d2)


It is no great vindication for me that Metanorma-generated White papers will be better documents than those generated by using the IEEE template. IEEE should be testing their own templates to begin with. And their designers should be a lot more familiar with Word functionality. 

Updating these is going to prove nightmarish, and I will not be doing so until we have demonstrated usage of these.

**Comment by opoudjis** [comment]
I'm intervening in the template ToC styles to supply an additional tab stop for the section numbers.

**Comment by opoudjis** [comment]
Work on this ticket is done, now need to implement unit testing.
