### ISSUE TITLE
Enabling two different lists of WG participants

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-ieee#72]
Current template for Participants section is organized to list chair and vice chair, participants of WG, participants of balloting group, etc.

Things get more complicated in IEEE 2830-2021. In here, we have two lists of participants - first WG participants as companies, then WG participants as persons.

![image](https://user-images.githubusercontent.com/55683568/176762627-91fd6f50-dd9d-43ea-9a73-c22eba0ebdad.png)

Currently, we don't have two different document attributes to separate these.

**Comment by anermina** [comment]
The other draft document of IEEE 2830 includes even organization + name of the representative:
![image](https://user-images.githubusercontent.com/55683568/176764666-32325a0a-b424-4ddd-86a7-3688a5038e49.png)

Maybe @ronaldtse could help with information which of these two options we expect in IEEE documents - organization names only, or names of the representatives for each as well.

**Comment by ronaldtse** [comment]
I have to say that this looks like a GB standard instead of an IEEE standard. Every organization and person on this list is from mainland China. 🤣 

For the published version, I think this is the case of OGC differentiating between "submitting organizations" and "participants". In IEEE, some working groups have organizational members and individual members. I think we can keep them in two separate attributes.

I feel that it might not be typical to have the "individual name ... org name" pairs, but if we are to have that, we could encode them as:

```
submitting-organization-2:Alibaba China Co. Ltd.
submitting-organization-individual-2:HONG, Cheng
```

Then:
* in the draft, render `{submitting-organization-2} ...... {submitting-organization-individual-2}`
* in the published version, render just `{submitting-organization-2}`

**Comment by ronaldtse** [comment]
Also, note that we need to semantically differentiate the given names/surnames of the participant, hence the proposal earlier to have the names split by a comma.

**Comment by opoudjis** [comment]
This is an artefact of people treating Word documents as blank canvases, and coming up with whatever perverse formatting they feel like this morning. I am declining to do the org + name table: this is opening the window up to any number of idiosyncratic renderings, which we simply cannot anticipate. This is the kind of thing that has to be negotiated by arrangement with IEEE editorial as is; let them do that negotiation through Word.

We also don't have any guarantee of the "gratefully acknowledges" wording recurring. Currently, I'm going to decline to realise that either. This needs to be managed, and it needs to be managed by IEEE; as it stands, it is in violation of their existing template.

I have been bogged down for five weeks in this flavour, and I have not yet even done Amendments. There are limits to how accomodating I am prepared to be.

The only concession I am prepared to make is to differentiate individual members and organisation members. Individual members are `wg-members`; organisation members shall be `wg-org-members`.

**Comment by opoudjis** [comment]
Drat.

https://standards.ieee.org/about/policies/opman/sect8/

Working group members and Standards Association ballot group members are listed in the front matter of the published IEEE standard. For entity-based standards, entities are listed and may be accompanied by the individual representing the entity.

We are going to have to insist on _*ONE*_ way of presenting people representing entities. The addle-headed disarray on display in these documents, where every standards editor comes up with their own format for presenting memberships, shall not be permitted in Metanorma. And the onus is on IEEE to provide an appropriate template.

**Comment by ronaldtse** [comment]
We may need some slight adjustment here. 

I do not know how to list out WG participants, whether it is an individual-based or entity-based WG. We will consult IEEE.

Otherwise, we can establish the following for the balloting group.

Basic facts:
1. There are 2 types of IEEE working groups: entity vs individual.
2. In an IEEE working group, there are participant members vs balloting/voting members. 
3. It seems that the ballot group can have members not in the working group. 

## Sample presentation of individual-based working group

(IEEE Std 1680.1a-2020)
<img width="618" alt="Screenshot 2022-07-11 at 3 06 15 PM" src="https://user-images.githubusercontent.com/11865/178199202-22a62d41-49df-44cc-8eb5-406fbe4d81fe.png">

## Sample presentation of entity-based working group

(IEEE Std 1800.2-2020)
<img width="620" alt="Screenshot 2022-07-11 at 3 24 12 PM" src="https://user-images.githubusercontent.com/11865/178201486-cfade236-1acb-4aab-abc9-ea8d764fa902.png">


## Summary

1. Will consult IEEE on how to display participants (will start a new ticket)
2. Ballot groups can contain individual names or organization names. When showing individual names, we need to differentiate the first and last names.

**Comment by opoudjis** [comment]
The tabular presentation that Nermina found appears to be the canonical presentation.

**Comment by opoudjis** [comment]
As said in https://github.com/metanorma/metanorma-ieee/issues/94 : we are doing away with all the daft idiosyncratic document attributes for participants: they are simply unsustainable. There will be either lists with minimal metadata, or as looks increasingly likely, YAML.

**Comment by opoudjis** [comment]
Mark the first list up as:

````
item::
name::: Jin Peng
role::: Chair
item::
name::: Chang Hong
role::: Vice Chair
item::
company::: Alibaba China Co. Ltd.
item::
company::: Alipay (China) Technology Co., Ltd.

...

The Working Group gratefully acknowledges the contributions of the following participants. Without their assistance and dedication, this standard would not have been completed.

* Xiaoyuan Bai
* Yang Bian
* Wenting Chang
....
````

Note: Normal lists are treated as equivalent to: 

````
item::
name::: X
role::: Member
````

For the other document, you can put in both name and company attributes:

````
item::
name::: Cheng Hong
company::: Alibaba China Co. Ltd.
````

I have not worked out yet how to render it.

We are doing away with all the document attributes for participants.

**Comment by ronaldtse** [comment]
Remember we need to differentiate surname and given names too, so we need a comma at the right place.

**Comment by opoudjis** [comment]
Not yet. I will deal with that later, you created another ticket for it.

**Comment by ronaldtse** [comment]
I have updated the participants guidance in https://github.com/metanorma/metanorma.org/pull/628

@opoudjis please have a look.

**Comment by opoudjis** [comment]
refactor clausedelimspace (tab in PresentationXML) to add node it is located in, so that HTML can do context-sensitive parsing of tabs.
