### ISSUE TITLE
Compilation failure on `related:contrast[]` markup

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-ieee#74]
In relation to https://github.com/metanorma/mn-samples-ieee/issues/1 and https://github.com/metanorma/mn-samples-ieee/pull/4

Following definition:

![issue2](https://user-images.githubusercontent.com/33627611/176809636-e8c1bb14-a8b2-44de-bb08-9ad0520c9131.PNG)

is encoded as:
````
==== input reference axis (IRA)
related:contrast[output reference axis]

The direction of an axis.

NOTE: See 6.7. footnote:[Notes in text, tables, and figures of a standard
are given for information only and do not contain requirements needed
to implement this standard.]
````

This results in compilation failure because the definition "output reference axis" doesn't exist.
But maybe this behavior should not occur? Wouldn't be better to show out a warning message?

**Comment by opoudjis** [comment]
It should exist in better regulated standards, but IEEE has a catch-all of what is not locally cited is cited elsewhere. I'll issue a warning in the case of IEEE.

**Comment by ronaldtse** [comment]
The key issue here is:
* a referenced term in **bold** does not mean the term exists in the current document, because it can reside on the IEEE SA Dictionary as described in the Footnote.
<img width="727" alt="Screenshot 2022-07-04 at 12 32 40 PM" src="https://user-images.githubusercontent.com/11865/177076884-979825f8-c1c2-437f-9b9a-f08b996168ad.png">

"IEEE Standards Dictionary Online is available at: http://dictionary.ieee.org/. An IEEE Account is required for access to the dictionary, and one can be created at no charge on the dictionary sign-in page"

We have no way of knowing whether this item exists without Metanorma having direct access to the dictionary (as of now).

It looks like this after logging in:
<img width="949" alt="Screenshot 2022-07-04 at 12 34 16 PM" src="https://user-images.githubusercontent.com/11865/177077022-805f072c-6418-460b-85f7-52bc91f07f3c.png">

**Comment by opoudjis** [comment]
In general case (isodoc): if related term not found, render warning string in document, **RELATED TERM NOT FOUND**. (A warning is already issued in standoc).

In IEEE, the term will be output anyway, since there is no linking.

**Comment by ronaldtse** [comment]
Confirm that "contrast" is now available.

Word:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/11865/177917555-2ddb1851-c8df-4949-ae98-017f67b1c080.png">

PDF:
<img width="612" alt="Screenshot 2022-07-08 at 1 34 48 PM" src="https://user-images.githubusercontent.com/11865/177917567-b1729b78-b3b3-448a-abdf-5c7c62a9208b.png">
